module.exports = {
  'absolute': ['absolutna', 'absosmerfna'],
  'aqua': ['wodny', 'wodna', 'wodne'],
  'beige': ['beżowy', 'beżowa', 'beżowe'],
  'bisque': ['biszkoptowy', 'biszkoptowa', 'biszkoptowe'],
  'black': ['czarny', 'czarna', 'czarne'],
  'blue': ['niebieski', 'niebieska', 'niebieskie'],
  'bold': ['ważny', 'ważna', 'ważne'],
  'brown': ['brązowy', 'brązowa', 'brązowe'],
  'center': 'środek',
  'chocolate': ['czekoladowy', 'czekoladowa', 'czekoladowe'],
  'cornflowerblue': ['modry', 'modra', 'modre'],
  'crimson': ['karmazynowy', 'karmazynowa', 'karmazynowe', 'karmazynowy-przypływ'],
  'fixed': 'zafiksowana',
  'gold': ['złoty', 'złota', 'złote'],
  'gray': ['szary', 'szara', 'szare'],
  'green': ['zielony', 'zielona', 'zielone'],
  'hidden': ['ukryty', 'ukryta', 'ukryte'],
  'inset': ['wkład', 'wklejka'],
  'italic': ['kursywa', 'włoski'],
  'left': ['lewy', 'lewa', 'lewo'],
  'no-repeat': 'nie-powtarzaj',
  'none': ['brak', 'żaden', 'nic'],
  'orange': ['pomarańczowy', 'pomarańczowa', 'pomarańczowe'],
  'pink': ['różowy', 'różowa', 'różowe'],
  'px': ['piksel', 'piksele', 'pikseli'],
  'red': ['czerwony', 'czerwona', 'czerwone'],
  'relative': 'relatywna',
  'repeat': 'powtarzaj',
  'right': ['prawy', 'prawa', 'prawo'],
  'silver': ['srebrny', 'srebrna', 'srebrne'],
  'solid': ['jednolita', 'jednolity'],
  'white': ['biały', 'biała', 'białe'],
  'yellow': ['żółty', 'żółta', 'żółte']
}
